# fly.toml app configuration file generated for comp7940-chatbot-talent-24434477-lhw on 2025-03-18T12:17:30+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'comp7940-chatbot-talent-24434477-lhw'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [services.ports]
    handlers = ["tls","http"]
    port = 443

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
